# Generated by Django 2.2.7 on 2021-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210102_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
